//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FightClub5eXMLBuilder.Core.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("compendium", Namespace="", IsNullable=false)]
    public partial class compendiumType {
        
        private object[] itemsField;
        
        private sbyte versionField;
        
        private bool versionFieldSpecified;
        
        private string auto_indentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("background", typeof(backgroundType))]
        [System.Xml.Serialization.XmlElementAttribute("class", typeof(classType))]
        [System.Xml.Serialization.XmlElementAttribute("feat", typeof(featType))]
        [System.Xml.Serialization.XmlElementAttribute("item", typeof(itemType))]
        [System.Xml.Serialization.XmlElementAttribute("monster", typeof(monsterType))]
        [System.Xml.Serialization.XmlElementAttribute("race", typeof(raceType))]
        [System.Xml.Serialization.XmlElementAttribute("spell", typeof(spellType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string auto_indent {
            get {
                return this.auto_indentField;
            }
            set {
                this.auto_indentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class backgroundType {
        
        private object[] itemsField;
        
        private ItemsChoiceType7[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("trait", typeof(traitType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType7[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traitType {
        
        private string[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attack", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("recharge", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("special", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        attack,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        proficiency,
        
        /// <remarks/>
        recharge,
        
        /// <remarks/>
        special,
        
        /// <remarks/>
        text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class monsterType {
        
        private object[] itemsField;
        
        private ItemsChoiceType9[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ac", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("action", typeof(traitType))]
        [System.Xml.Serialization.XmlElementAttribute("alignment", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("cha", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("con", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("conditionImmune", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("dex", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("environment", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("hp", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("immune", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("int", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("languages", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("legendary", typeof(traitType))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("passive", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("reaction", typeof(traitType))]
        [System.Xml.Serialization.XmlElementAttribute("resist", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("save", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("senses", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("size", typeof(sizeEnum))]
        [System.Xml.Serialization.XmlElementAttribute("skill", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("slots", typeof(slotsType))]
        [System.Xml.Serialization.XmlElementAttribute("speed", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("spells", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("str", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("trait", typeof(traitType))]
        [System.Xml.Serialization.XmlElementAttribute("type", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("vulnerable", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("wis", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType9[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum sizeEnum {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        G,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class slotsType {
        
        private string optionalField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType9 {
        
        /// <remarks/>
        ac,
        
        /// <remarks/>
        action,
        
        /// <remarks/>
        alignment,
        
        /// <remarks/>
        cha,
        
        /// <remarks/>
        con,
        
        /// <remarks/>
        conditionImmune,
        
        /// <remarks/>
        cr,
        
        /// <remarks/>
        description,
        
        /// <remarks/>
        dex,
        
        /// <remarks/>
        environment,
        
        /// <remarks/>
        hp,
        
        /// <remarks/>
        immune,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        languages,
        
        /// <remarks/>
        legendary,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        passive,
        
        /// <remarks/>
        reaction,
        
        /// <remarks/>
        resist,
        
        /// <remarks/>
        save,
        
        /// <remarks/>
        senses,
        
        /// <remarks/>
        size,
        
        /// <remarks/>
        skill,
        
        /// <remarks/>
        slots,
        
        /// <remarks/>
        speed,
        
        /// <remarks/>
        spells,
        
        /// <remarks/>
        str,
        
        /// <remarks/>
        trait,
        
        /// <remarks/>
        type,
        
        /// <remarks/>
        vulnerable,
        
        /// <remarks/>
        wis,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class spellType {
        
        private object[] itemsField;
        
        private ItemsChoiceType8[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classes", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("components", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("duration", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("level", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("range", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ritual", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("roll", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("school", typeof(schoolEnum))]
        [System.Xml.Serialization.XmlElementAttribute("source", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("time", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType8[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum schoolEnum {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        EV,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType8 {
        
        /// <remarks/>
        classes,
        
        /// <remarks/>
        components,
        
        /// <remarks/>
        duration,
        
        /// <remarks/>
        level,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        range,
        
        /// <remarks/>
        ritual,
        
        /// <remarks/>
        roll,
        
        /// <remarks/>
        school,
        
        /// <remarks/>
        source,
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        time,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class featType {
        
        private object[] itemsField;
        
        private ItemsChoiceType6[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modifier", typeof(modifierType))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("prerequisite", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("special", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType6[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifierType {
        
        private categoryEnum categoryField;
        
        private bool categoryFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public categoryEnum category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified {
            get {
                return this.categoryFieldSpecified;
            }
            set {
                this.categoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum categoryEnum {
        
        /// <remarks/>
        bonus,
        
        /// <remarks/>
        Bonus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ability score")]
        abilityscore,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ability Score")]
        AbilityScore,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ability modifier")]
        abilitymodifier,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ability Modifier")]
        AbilityModifier,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("saving throw")]
        savingthrow,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Saving Throw")]
        SavingThrow,
        
        /// <remarks/>
        skills,
        
        /// <remarks/>
        Skills,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType6 {
        
        /// <remarks/>
        modifier,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        prerequisite,
        
        /// <remarks/>
        proficiency,
        
        /// <remarks/>
        special,
        
        /// <remarks/>
        text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class classType {
        
        private object[] itemsField;
        
        private ItemsChoiceType5[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("armor", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("autolevel", typeof(autolevelType))]
        [System.Xml.Serialization.XmlElementAttribute("hd", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("numSkills", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("slotsReset", typeof(resetEnum))]
        [System.Xml.Serialization.XmlElementAttribute("spellAbility", typeof(abilityEnum))]
        [System.Xml.Serialization.XmlElementAttribute("tools", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("wealth", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("weapons", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType5[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autolevelType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string levelField;
        
        private string scoreImprovementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("counter", typeof(counterType))]
        [System.Xml.Serialization.XmlElementAttribute("feature", typeof(featureType))]
        [System.Xml.Serialization.XmlElementAttribute("slots", typeof(slotsType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scoreImprovement {
            get {
                return this.scoreImprovementField;
            }
            set {
                this.scoreImprovementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class counterType {
        
        private object[] itemsField;
        
        private ItemsChoiceType4[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("reset", typeof(resetEnum))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType4[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum resetEnum {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        S,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType4 {
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        reset,
        
        /// <remarks/>
        value,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class featureType {
        
        private object[] itemsField;
        
        private ItemsChoiceType3[] itemsElementNameField;
        
        private string optionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modifier", typeof(modifierType))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("special", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType3[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType3 {
        
        /// <remarks/>
        modifier,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        proficiency,
        
        /// <remarks/>
        special,
        
        /// <remarks/>
        text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum abilityEnum {
        
        /// <remarks/>
        Strength,
        
        /// <remarks/>
        Dexterity,
        
        /// <remarks/>
        Constitution,
        
        /// <remarks/>
        Intelligence,
        
        /// <remarks/>
        Wisdom,
        
        /// <remarks/>
        Charisma,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType5 {
        
        /// <remarks/>
        armor,
        
        /// <remarks/>
        autolevel,
        
        /// <remarks/>
        hd,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        numSkills,
        
        /// <remarks/>
        proficiency,
        
        /// <remarks/>
        slotsReset,
        
        /// <remarks/>
        spellAbility,
        
        /// <remarks/>
        tools,
        
        /// <remarks/>
        wealth,
        
        /// <remarks/>
        weapons,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class raceType {
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ability", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("modifier", typeof(modifierType))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("size", typeof(sizeEnum))]
        [System.Xml.Serialization.XmlElementAttribute("speed", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("spellAbility", typeof(abilityEnum))]
        [System.Xml.Serialization.XmlElementAttribute("trait", typeof(traitType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        ability,
        
        /// <remarks/>
        modifier,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        proficiency,
        
        /// <remarks/>
        size,
        
        /// <remarks/>
        speed,
        
        /// <remarks/>
        spellAbility,
        
        /// <remarks/>
        trait,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class itemType {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ac", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("detail", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("dmg1", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("dmg2", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("dmgType", typeof(damageEnum))]
        [System.Xml.Serialization.XmlElementAttribute("magic", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("modifier", typeof(modifierType))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("property", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("range", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("roll", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("stealth", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("strength", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("type", typeof(itemEnum))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("weight", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum damageEnum {
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        FC,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum itemEnum {
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        HA,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        RD,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        WD,
        
        /// <remarks/>
        RG,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("$")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        ac,
        
        /// <remarks/>
        detail,
        
        /// <remarks/>
        dmg1,
        
        /// <remarks/>
        dmg2,
        
        /// <remarks/>
        dmgType,
        
        /// <remarks/>
        magic,
        
        /// <remarks/>
        modifier,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        property,
        
        /// <remarks/>
        range,
        
        /// <remarks/>
        roll,
        
        /// <remarks/>
        stealth,
        
        /// <remarks/>
        strength,
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        type,
        
        /// <remarks/>
        value,
        
        /// <remarks/>
        weight,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType7 {
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        proficiency,
        
        /// <remarks/>
        trait,
    }
}
